### PR TITLE
feat: callback on file

### PR DESCRIPTION
**Pull request by AndersDJohnson**
Supports https://github.com/dependents/node-dependency-tree/issues/147.

These new callback options `onFile` and `onAfterFile`, in combination with https://github.com/dependents/node-dependency-tree/pull/149 and https://github.com/dependents/node-precinct/pull/111, will give external consumers enough info to know the position in the graph as `node-dependency-tree` crawls the project, with full access to the AST and other metadata for each processed file, on top of which we can build our own functionality.

This should eliminate the need for a lot of other feature requests.

Can enhance tests and documentation for this once we have conceptual approval.

We can slowly add this to other detective packages, like the various JavaScript module systems.

Example usage:

Suppose we have a metadata object to track data about each file we process (maybe in real code we would use a `Map`):
```ts
const metadata = {};
```
Then suppose we call the detective with this `onFile` function:
```ts
    {
      onFile: (data) => {
        const { ast, walker, options } = data;
        const { filename, treePath } = options;

        // Our key in the map
        const metadataKey = [...treePath, filename].join(" > ");
        
        const localMetadata = {};

        metadataMap[localMetadata] = {};

        try {
          walker.walk(ast, (node) => {
            // Check for more stuff in the file...

            localMetadata.type = node.type;
          });
        } catch (error) {
          console.error("*** error", error);
        }
      },
   }
```

Now our `metadata` will look something like this:

```ts
{
  '/Users/anders/code/app/App.tsx': { type: 'Literal' },
  '/Users/anders/code/app/App.tsx > /Users/anders/code/app/components/Header.tsx': { type: 'Literal' },
  '/Users/anders/code/app/App.tsx > /Users/anders/code/app/components/Header.tsx > /Users/anders/code/app/components/Title.tsx': { type: 'Identifier' },
  '/Users/anders/code/app/App.tsx > /Users/anders/code/app/components/Footer.tsx': { type: 'Literal' }
}
```

### CODE REVIEW

**Comment by AndersDJohnson** [comment]
@mrjoelkemp Thanks! The difference is that `onAfterFile` includes the `dependencies` result, unlike `onFile`. I'm willing to consolidate on just `onAfterFile` if you like. Wasn't sure if there would be use cases for both, now or in future.

**Comment by mrjoelkemp** [comment]
Whatever you think is best. Thanks for clarifying

**Comment by AndersDJohnson** [comment]
@mrjoelkemp Thanks! Just adding the options to the README (see 890d412967085773bc61bacee99f0179c1c91ba8). Let me know what you think and anything else needed before we can merge!

**Comment by AndersDJohnson** [comment]
@mrjoelkemp Sorry to bother. Wondering if you had any more thoughts on this, or if we're good to merge & release? I'm happy to step in as a maintainer as well if you like. Or I suppose I could fork & publish for my purposes, but would prefer to support your main line project!

**Comment by AndersDJohnson** [comment]
@XhmikosR Are you maintaining now? Thanks!

**Comment by XhmikosR** [comment]
Not really, just had some time and decided to merge a couple of changes. @mrjoelkemp should have a look at this :)

**Pull request merged**
