### PR TITLE
Update dependencies and drop Node.js < 18 support

### PR DESCRIPTION
**Pull request by XhmikosR**
There's a test failure in https://github.com/dependents/detective-typescript/blob/cf5ccf12744dc03bf830a789018f1d13c300c3a5/index.js#L80C9-L80C75

Any help is welcome to fix the issue so that we can update the deps

### CODE REVIEW

**Comment by waivital** [comment]
In [this commit](https://github.com/typescript-eslint/typescript-eslint/commit/2b69b659d87b58468e413801d31086ae0eeafff4#diff-d17371cd74cdb8eb7288346bce5a663f57d55b40388b55e6cacb634e1998c353), `@typescript-eslint/typescript-estree` made updates to the structure of `TSImportType`. Specifically, it removed the `parameter` and `isTypeOf` attributes and replaced them with the term `argument`. Applying the following changes will make the test pass again.

```
       case 'TSImportType': {
-        if (!skipTypeImports && node.parameter.type === 'TSLiteralType') {
-          dependencies.push(node.parameter.literal.value);
+        if (!skipTypeImports && node.argument.type === 'TSLiteralType') {
+          dependencies.push(node.argument.literal.value);
         }
```

**Comment by XhmikosR** [comment]
Thanks a lot @waivital !

**Comment by waivital** [comment]
Glad to help😄

**Comment by XhmikosR** [comment]
Released as [v12.0.0](https://github.com/dependents/detective-typescript/releases/tag/v12.0.0)

**Pull request merged**
