### PR TITLE
Add supports for ignore named imports and exports

### PR DESCRIPTION
**Pull request by waivital**
When the `skipTypeImports` option is enabled, only ignoring type imports is not sufficient. With TypeScript 4.5, it also supports named type imports and named type exports.

### CODE REVIEW

**Comment by XhmikosR** [comment]
While you have added tests, I'm not super familiar with the changes to be able to review your PR. Maybe someone else can review it.

**Comment by waivital** [comment]
Okay, and let me also add more context to this changes.

It's an extend to this [PR](https://github.com/dependents/detective-typescript/pull/20) which  originally added the option `skipTypeImports`. I think the idea behind this changes is the [type-only imports and export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)  will not actually contribute to the dependancy graph after typescript get comipled to javascript, so sometimes when analyzing dependencies, being able to skip these type-only dependencies will make the output simpler.

When [TypeScript 4.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names) is released, it allows a type modifier on individual named imports. If this new syntax is used in the code, the old logic for `skipTypeImports` will not take effect.

**Comment by XhmikosR** [comment]
Let's try this one, the logic LGTM!

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
Released as https://github.com/dependents/detective-typescript/releases/tag/v11.2.0, I hope we didn't break anything 🙂

**Pull request merged**
